### ISSUE TITLE
테마, 스크롤바 클라이언트에서 처리

### ISSUE THREAD

**Issue by pekochan069** [yiminwook/liveuta#106]
서버랑은 관련이 없는 부분이니까 클라에서 처리

나중에 ppr 등으로 좀 더 빠른 첫 로딩이 가능해짐

**Comment by yiminwook** [comment]
테마는 html 태그에 초기값 안주면 다크모드에서 눈뽕 맞던데

**Comment by pekochan069** [comment]
그것도 해결 가능함
next에서 해본건 아니긴 한데 우타툴즈에서 그렇게 하고있음

**Comment by pekochan069** [comment]
생각보다 쉽지가 않네
하다보니까 next-theme을 재창조하고있음
일단 보류
