### ISSUE TITLE
세트리스트 페이지에 채널명이 안 나옴

### ISSUE THREAD

**Issue by pekochan069** [yiminwook/liveuta#114]
제곧내

**Comment by yiminwook** [comment]
/v1/channel size 기본값이 1이라서 안나오는듯 일단 다 풀음

**Comment by yiminwook** [comment]
세트리 상세 유투버채널 이미지가 안나옴

**Comment by yiminwook** [comment]
캐릭터에 걸은 img style이 Avatar img에도 영향이 가서 classname으로 수정함

d3a9064
