### ISSUE TITLE
스케쥴 탭에서 블록한 채널이 홈-현재라이브중에는 계속 노출되는 문제

### ISSUE THREAD

**Issue by utawakuworker** [yiminwook/liveuta#115]
이거 우선순위 할당하는건 없든가 confluence에만 잇나....

**Comment by yiminwook** [comment]
라이브중에서 블랙리스트 필터링 안하던거 고침

즐겨찾기는 즐겨찾기랑, 블랙리스트 동시에 되어있을때 즐겨찾기가 우선순위 더 높게 설계해둔거라서 

보이는게 맞음, 마이페이지 블랙리스트도 보이게 고침

**Comment by utawakuworker** [comment]
아 우선순위 이야기는 이슈 자체의 우선순위 ㅋㅋ

**Comment by utawakuworker** [comment]
https://github.com/yiminwook/liveuta/commit/ddae1e89f0160a2898e5bb6a053d9534969135bc

참고용 커밋로그
