### ISSUE TITLE
파이어폭스에서 홈 cover image 보이지 않는 현상

### ISSUE THREAD

**Issue by utawakuworker** [yiminwook/liveuta#125]
![image](https://github.com/user-attachments/assets/a26942b9-2cf7-4c7f-8cb3-31290eeaade7)

다른 브라우저에서는 잘 보이는걸로 보아 파폭 이슈 or 무언가 내 설정 이슈일 가능성도 높은

우선순위가 높지는 않으니까 그냥 그런게 있다 정도로 알고있으면 되지않을까....

**Comment by utawakuworker** [comment]
*덕덕고/크롬 등 다른 브라우저에서는 정상적으로 나옴

**Comment by utawakuworker** [comment]
http://gall.dcinside.com/mini/board/view/?id=vuta&no=156288 

뭔가 내 쪽 이슈인걸로....

**Comment by yiminwook** [comment]
브라우저 개발자도구 스샷가능?

**Comment by utawakuworker** [comment]
> 브라우저 개발자도구 스샷가능? 이미지 스타일쪽

콘텐츠 차단이 켜져 있어서 “https://pbs.twimg.com/media/GfkzPQVa0AAD11k?format=jpg&name=large”에 있는 리소스가 차단되었습니다.

이건데.. 파폭 엄격모드에서 뭔가 차단하는게 있는듯

**Comment by yiminwook** [comment]
그럼 딴이미지로 바꿔보실?

**Comment by utawakuworker** [comment]
그냥 엄격모드 끄면 보여 관련 내용은 https://developer.mozilla.org/en-US/docs/Web/Privacy/Firefox_tracking_protection 이거긴 한데... 딱히 신경 안 써도 될듯?
