### ISSUE TITLE
제목, 유튜브 링크가 각각 다른 길이를 가짐

### ISSUE THREAD

**Issue by pekochan069** [yiminwook/liveuta#4]
설명 수정할 때는 괜찮아 보였는데 이제보니 별로 안괜찮은것 같기도 하네
`text-overflow: ellipsis`를 이용해 한 줄로 축약을 하는것도 괜찮아보임.

**Comment by yiminwook** [comment]
```
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow:`hidden;
```
위 코드를 써서 css적으로 말줄임 처리를 하면 width-middle 이하 모바일화면에서 확대가 납니다
서버에서 40자로 잘라서 이미 처리를 하고 있는데 글자를 더 잘라낼지 css코드를 추가로 더 써야하는지 
잘 모르겠네요

**Comment by pekochan069** [comment]
모바일은 놔두고 middle 이상에서 description 높이를 2em으로, 유튜브 링크를 1em으로 제한하면 괜찮지 않을까요. 특정 방송의 방송제목이 3줄 이상일 때 1줄짜리랑 너무 차이가 크다고 느낌

**Comment by yiminwook** [comment]
일단 해결
