### ISSUE TITLE
녹색 테마에서 상단 네비게이션 바의 색상 대비 문제

### ISSUE THREAD

**Issue by pekochan069** [yiminwook/liveuta#52]
![image](https://github.com/yiminwook/liveuta/assets/97679910/5cbc5d4f-2343-43e9-b9ae-a40060acb6bd)

녹색 테마를 적용했을 때 글씨가 잘 안보임. 특히 hover 상태일 때는 녹색 배경에 노란색 글씨라 더 잘 안보임

색상 변경이 필요해 보임

**Comment by yiminwook** [comment]
임시로 초록색으로 변경했는데 다른데서도 쓰고 있는 공통으로 사용하는 컬러라, 장기적으로는 컬러를 더 세분화 할 예정임
