### ISSUE TITLE
검색 결과로 반환되는 일부 채널 @handle 제대로 동작하지 않는 문제

### ISSUE THREAD

**Issue by utawakuworker** [yiminwook/liveuta#73]
예) 헤가 

원래 핸들은 @0hega인데 채널 주인이 연결을 제대로 안했는지 아니면 다른 이슈인지 접속이 안됨

전에 핸들 변경한 건으로 누가 수정 요청한것도 있고 해서, combinedChannelData에서 combinedSheetDataValues 반환할때 url은 빼버리고 youtube.com/channel/channel_id 형태로 받으면 좋을듯....

**Comment by yiminwook** [comment]
혹시 이거 크리티컬함? 지금 로그인 구현중이라 한동안은 정신없을 것 같아서

**Comment by utawakuworker** [comment]
아니 전혀?? 잊어도 돼 ㅋㅋ 뭣하면 내가 해도 되구



다운로드 Android용 BlueMail



2024년 2월 27일 20:50, 20:50, Minwook_Yi ***@***.***> 작성:
