### ISSUE TITLE
모바일 환경(firerox/android)에서 현재 시청자수 표시되지 않음

### ISSUE THREAD

**Issue by utawakuworker** [yiminwook/liveuta#79]
![Screenshot_20240302_120958_Firefox](https://github.com/yiminwook/liveuta/assets/136960279/e5451592-4fd2-4256-aa4e-476ecdea39e6)

의도된사양인가요???

**Comment by yiminwook** [comment]
아뇨 CORS 문제는 아닌것 같은데 요청할때 헤더가 달라서 그런것 같습니다. 이것저것 해보고 있어요

**Comment by utawakuworker** [comment]
일단 안 닫고 잠깐 냅둘게~

**Comment by yiminwook** [comment]
크롬 열고 개발자 도구에서 모바일로 하면 응답이 ? 로오는데 왠지 모르겠음 데탑으로 하면 잘옴 
모바일이라고해서 프론트 fetch 코드가 다르진 않은데

**Comment by yiminwook** [comment]
나 나가야되서 라이브우타에 worker.js 올려놓음 코드보고 싶으면 확인해줘

**Comment by yiminwook** [comment]
고침User-Agent 지우니까 되네
