### ISSUE TITLE
prettier 대신 Biome 사용

### ISSUE THREAD

**Issue by pekochan069** [yiminwook/liveuta#90]
[Biome](https://biomejs.dev/)

포매터랑 린터가 합쳐져있어서 eslint랑 prettier를 둘 다 대체할 수 있는데 훨씬 빠름
포매터만 Biome으로 바꾸고 eslint는 계속 사용해도 되고

### 설치

```sh
pnpm i -D @biomejs/biome
pnpx @biomejs/biome init
pnpx @biomejs/biome migrate prettier --write
```

### vscode 설정 업데이트

`.vscode/settings.json`
```json
{
  "typescript.tsdk": "node_modules/typescript/lib",
  "editor.codeActionsOnSave": {
    "source.organizeImports.biome": "explicit",
    "quickfix.biome": "explicit"
  },
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
}
```

Biome 익스텐션 설치

### 설정 변경 시

[바이옴 설정](https://biomejs.dev/guides/configure-biome/)
[포매터 옵션](https://biomejs.dev/formatter/#options)
[린터 룰](https://biomejs.dev/linter/rules/)

린터 룰 변경하려면

`biome.json`
```diff
{
  …
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
+     "complexity": {
+       "noForEach": "off"
+     }
    }
  }
  …
}
```

와 같이 하면 됨

### 린터 비활성화

린터를 biome 대신 기존에 쓰던 eslint를 계속 사용하려면 `biome.json`에서 `linter`를 비활성화

`biome.json`
```diff
{
  …
  "linter": {
-   "enabled": true,
+   "enabled": false,
    "rules": {
      "recommended": true
    }
  },
  …
}
```

### 번외

vscode 익스텐션 추천에 뜨게 하기

`extensions.json`
```json
{
  "recommendations": [
    "biomejs.biome"
  ]
}
```

**Comment by yiminwook** [comment]
lint는 nextjs에서 next/core-web-vitals를 대체할 수 있는지 잘 모르겠어서 일단 fomatter만 바꾸고 나중에 lint까지 바꿔보는걸로 생각중

** 그외로 autoSync  커밋 확인했는데 옵션 설정이 문제될 수 있을 것 같아서 약간 변경했음. 

 - gc랑 stale time 너무 길면 다른 페이지에도 데이터가 old한 데이터가 들어갈 수 있어서 변경했고
  - refetchInterval는 true일시 제대로 동작 안해서 변경함.

**Comment by pekochan069** [comment]
확인
