### ISSUE TITLE
Next.js 15 업데이트

### ISSUE THREAD

**Issue by pekochan069** [yiminwook/liveuta#92]
react 19로 같이 업데이트

mantine 등 일부 라이브러리들은 아직 react19로 업데이트 안함

업데이트 해본 결과 빌드 속도가 굉장히 빨라짐

`next dev` `--turbopack`은 sass를 어떻게 적용시켜야 하는건지 모르겠어서 비활성화. 그래도 빠름

**Comment by yiminwook** [comment]
터보팩은 현재 웹팩 설정을 호환 안되는게 많아서    당장은 못쓸듯 SVGR이랑 css문법 몇가지 안된다고 그러던데

**Comment by yiminwook** [comment]
7412c85

브랜치 정리해둠, pull 부탁

**Comment by yiminwook** [comment]
489d5b8

sass migation merge

**Comment by yiminwook** [comment]
next15 추가로 더 작업할 거 남음?

**Comment by pekochan069** [comment]
리액트 컴파일러 건드려보고 있는데 모달에서 문제가 있어서 mantine 모달로 교체하는게 맞는지 그냥 리액트 컴파일러 빼고 쓰는게 맞는지 해보고있음
다른건 딱히 없는듯

**Comment by yiminwook** [comment]
useModalStore 말하는거?

**Comment by pekochan069** [comment]
ㅇㅇ 모달 열면 페이지를 전환해야 열리고 안 닫힘

**Comment by yiminwook** [comment]
문제되는 상황이랑 커밋찍어서 올려줄 수 있음? 나도 확인해보려고

**Comment by pekochan069** [comment]
react-forget 브랜치 팜

**Comment by yiminwook** [comment]
상황이  멀티뷰 추가할때 문제되는거?

**Comment by pekochan069** [comment]
다른 모달들도 다 그럼

**Comment by yiminwook** [comment]
```component/config/ModalProvier.tsx```

```diff
'use client';
import ModalContainer from '@/libraries/modal/ModalContainer';
import ModalContext from '@/libraries/modal/ModalContext';
import ModalController from '@/libraries/modal/ModalController';
import { PropsWithChildren, useState } from 'react';

export default function ModalProvider({ children }: PropsWithChildren) {
+  'use no memo';
  const renderState = useState(1);
  const [modalController] = useState(() => new ModalController(renderState));

  return (
    <ModalContext.Provider value={modalController}>
      <> {children}</>
      <ModalContainer />
    </ModalContext.Provider>
  );
}
```

modalProvicer가 리랜더링 안되서 그런듯 이렇게 수정하면 고쳐짐

지금처럼 async-await으로 모달열린 상태에서 js 중단점 걸 수 있으면 mantine 써도 상관없음

**Comment by pekochan069** [comment]
굳이 바꿀 필요는 없어보이니까 no memo만 하고 넘어가면 되겠네

**Comment by yiminwook** [comment]
@mantine/modals말고 그냥 modal ui는 쓸생각임

**Comment by yiminwook** [comment]
vercel 노드 패키지는 cli 쓰려고 받음?

**Comment by pekochan069** [comment]
아 그거 테스트할려고 설치했던건데 없에도 상관없음

**Comment by yiminwook** [comment]
next-15 브랜치 featured랑 합쳐도 상관없지?

**Comment by pekochan069** [comment]
ㅇㅇ

**Comment by yiminwook** [comment]
dev 브랜치에 합쳐놓음
