### ISSUE TITLE
page 이동시 마다 bottom-tab 위치가 움직이는 문제

### ISSUE THREAD

**Issue by yiminwook** [yiminwook/liveuta#98]
https://github.com/yiminwook/liveuta/blob/6e02a1f0e9dccf63ab32cf3eea0477da44b0cf75/src/styles/global.scss#L147

페이지 움직일때마다 모바일에서 위로 올라오는 애니메이션이 생각보다 눈이 아픈것 같고 과도하게 화면을 움직이는 것 같음

버텀탭에 애니메이션을 안걸리게 끔 하던가

애니메이션을 transform 거리을 더 줄여야 할 것 같음

https://liveuta-dev.vercel.app/

**Comment by pekochan069** [comment]
확인

**Comment by yiminwook** [comment]
![image](https://github.com/user-attachments/assets/4e0de0c4-43f5-4d56-b836-3142316e47a8)

모바일에서 스크롤바가 중첩되서 보임 

react-device-detect로 모바일 기기애서는 스크롤바 기본으로 하던가 해야할듯
