### ISSUE TITLE
모바일 기기 스크롤바 중첩

### ISSUE THREAD

**Issue by yiminwook** [yiminwook/liveuta#99]
<img src="https://github.com/user-attachments/assets/4e0de0c4-43f5-4d56-b836-3142316e47a8 " width="400"/>

모바일에서 스크롤바가 중첩되서 보임 

device-detect로 모바일 기기애서는 스크롤바 기본으로 하던가 해야할듯

https://nextjs.org/docs/pages/api-reference/functions/userAgent

또는 react-divice-detect

middleware는 과금 될 수 있어서 왠만하면 안되는 방법으로 찾아보면 좋을듯

**Comment by pekochan069** [comment]
일단 난 정상적으로 한개만 보임
https://uta-tools.vercel.app/ko/tools 여기서도 두개로 보이는지 확인좀

**Comment by pekochan069** [comment]
내가 아이폰이 없어서 ios 테스트를 못함
일단 의심되는건 `global.scss`랑 `overlayscrollbars.css` 순서 문제

**Comment by yiminwook** [comment]
> 일단 난 정상적으로 한개만 보임
> 
> https://uta-tools.vercel.app/ko/tools 여기서도 두개로 보이는지 확인좀

![image](https://github.com/user-attachments/assets/dbea3049-7f16-4192-88c6-caa10df60147)

**Comment by pekochan069** [comment]
overlayscrollbar 쓴게 view transitions 적용하면 스크롤바 없는 페이지랑 스크롤바 있는 페이지 전환할 때 레이아웃 변화때문에 바꾼건데, 이러면 그냥 빼고 데스크탑 레이아웃에서만 최소 높이를 101vh으로 놓고 쓴다던가 해야하나

**Comment by yiminwook** [comment]
https://github.com/KingSora/OverlayScrollbars/issues/622

이슈도 한번 올라왔던 내용인듯 한데 아예 없애는 편보다 safari에서 작동을 안하게 하는게 더 쉬울 것 같음

**Comment by yiminwook** [comment]
```typescript

'use client';

import { OverlayScrollbars } from 'overlayscrollbars';
import { useEffect } from 'react';

export default function GlobalScrollbar() {
  useEffect(() => {
    OverlayScrollbars(
      {
        target: document.body,
        cancel: {
          nativeScrollbarsOverlaid: true,
        },
      },
      {
        scrollbars: {
          autoHide: 'leave',
          autoHideSuspend: true,
        },
      },
    );
  }, []);
  return null;
}
```

nativeScrollbarsOverlaid: true 했는데 비활성화 안되네

**Comment by yiminwook** [comment]
cd95da7

모바일인지 확인할 수 있게 끔 분기처리를 했는데 비활성화 하는 방법을 모르겠음

**Comment by yiminwook** [comment]
```typesciprt
{
  ua: 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Mobile/15E148 Safari/604.1',
  browser: { name: 'Mobile Safari', version: '18.1.1', major: '18' },
  engine: { name: 'WebKit', version: '605.1.15' },
  os: { name: 'iOS', version: '18.1.1' },
  device: { vendor: 'Apple', model: 'iPhone', type: 'mobile' },
  cpu: { architecture: undefined },
  isBot: false
}
```

```console.log(userAgent({ headers: await headers() }));```

아이폰으로 콘솔 찍었을때 위와 같음
